### ISSUE TITLE
Missing Planet eStream Icon

### ISSUE THREAD

**Issue by AndyNicolle** [PlaneteStream/moodle-atto_planetestream#5]
We have installed the Planet eStream suite of plugins onto a Moodle 3.5.7 site and setup the atto plugin to include the eStream icon, but it is not appearing when trying to edit courses.

Moodle 3.5.7
Planet eStream Submission Plugin 6.35
Planet eStream Authentication Plugin 6.32
Planet eStream iFrame Filter 6.20
Planet eStream Atto 6.45
Planet eStream TinyMCE 6.45

I have tried changing the theme, I have also compared all settings and permissions/ownerships with another site where the plugins are working correctly, but I am unable to get the icon to appear on this site.

![estream1](https://user-images.githubusercontent.com/74614479/108493902-cfb3d300-729e-11eb-9300-bec116146c2d.png)
![estream2](https://user-images.githubusercontent.com/74614479/108493904-d04c6980-729e-11eb-9a0b-9f368c54293f.png)

**Comment by PlaneteStream** [comment]
Hi Andy,

The text editor plugins will perform a check against your eStream site before loading, if there is a problem connecting they will not show in the text editor.

This can happen due to one of two reasons:

1. Double check that the Planet eStream Assignment Submission Plugin is installed and pointed to your eStream website. The text editor plugins will inherit the eStream website URL from here.
2. The Moodle site IP address will need to be white listed to make requests against your eStream site. Check within the Tools > Admin > Integrations & Features > Plugin Options > Moodle and ensure that the IP address of your Moodle server is here. If you are cloud hosted please feel free to let me know the website URL and I'll check these from our side.

A final issue which is quite rare is that the Moodle server itself cannot contact your eStream site due to internet restrictions.

Please let me know if either of these options help and if you would like to drop us an email at support@planetestream.co.uk we can help directly.

**Comment by PlaneteStream** [comment]
Andy contacted via email where the issue was due to the Moodle server IP address not being whitelisted on the eStream side. 

The new Moodle server IP address was whitelisted which resolved the issue.
